name: install bukkit
on: push
env:
  repo: IngGameTeam/automate-bukkit
  ver: 1.19
  ram: 6500M
jobs:
  install-bukkit:
    runs-on: [ self-hosted, mc-home ]
    steps:
      - name: install-bukkit
        run: |
          rm -rf work
          mkdir work 
          cd work
          git clone https://${{ github.actor }}@github.com/${{ env.repo }}
          dir_name=$(basename ${{ env.repo }} /)
          cd $dir_name
          mkdir out
          mkdir out/bukkit
          cd out/bukkit
          git init
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.repo }}
          cd ..
          cd ..
          for file in bukkit; do
            cp -r $file out/bukkit/
          done
          cd out/bukkit
          cd bukkit
          wget -O purpur.jar https://api.purpurmc.org/v2/purpur/1.19/latest/download
          function plugin($url, $plugin) {
            latest=$(curl -sL https://api.github.com/repos/$url/releases/latest | jq -r ".tag_name")
            cd plugins
            wget https://github.com/$url/releases/download/$latest/$plugin-$latest.jar
          }
          plugin IntellectualSites/FastAsyncWorldEdit FastAsyncWorldEdit-Bukkit
          plugin ViaVersion/ViaVersion ViaVersion
          plugin ViaVersion/ViaBackwards ViaBackwards
          touch run.sh
          echo 'java -jar purpur.jar nogui' >> run.sh
          chmod +x ./run.sh
          ./run.sh
          rm -r eula.txt
          touch eula.txt
          echo 'eula=true' >> eula.txt 
          ./run.sh
          rm -rf run.sh
          touch run.sh
          echo 'java -Xms${{ env.ram }} -Xmx${{ env.ram }} -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar purpur.jar nogui' >> run.sh
          chmod +x ./run.sh
          rm -rf plugins/stop-on-start.jar 
          cd ..
          git checkout -b bukkit
          git add .
          git commit -m "done"
          git push origin bukkit --force
