name: install bukkit
on: push
env:
  repo: IngGameTeam/automate-bukkit
jobs:
  install-bukkit:
    runs-on: [ self-hosted, mc-home ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: mkdirs bukkit directory
        run: mkdir bukkit
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.repo }}
      - run: |
          for file in ./bukkit/; do
            cp -r $file bukkit/
          done
          cd bukkit
          git add .
          git commit -m "done"
          git push origin bukkit
