name: install bukkit
on: push
jobs:
  gradle:
    runs-on: [ self-hosted, mc-home ]
    steps:
      - name: checkout
        uses: actions/checkout@v2


      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './info.properties'
          property: 'directory'

      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "bukkit/*"
          target: "${{ steps.read_property.outputs.value }}"
