name: install bukkit
on: push
env:
  repo: IngGameTeam/automate-bukkit
jobs:
  install-bukkit:
    runs-on: [ self-hosted, mc-home ]
    steps:
      - run: |
          rm -rf work
          mkdir work 
          cd work
          git clone https://${{ github.actor }}@github.com/${{ env.repo }}
          dir_name=$(basename ${{ env.repo }} /)
          cd $dir_name
          mkdir out
          mkdir out/bukkit
          cd out/bukkit
          git init
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.repo }}
          cd ..
          cd ..
          for file in bukkit; do
            cp -r $file out/bukkit/
          done
          cd out/bukkit
          git checkout -b bukkit
          git add .
          git commit -m "done"
          git push origin bukkit --force
