name: install bukkit
on: push
env:
  repo: IngGameTeam/automate-bukkit
jobs:
  install-bukkit:
    runs-on: [ self-hosted, mc-home ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir out
          mkdir out/bukkit
          cd out/bukkit
          git init
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.repo }}
      - run: |
          for file in ./bukkit/; do
            cp -r $file out/bukkit/
          done
          cd out/bukkit
          git checkout -b bukkit
          git add .
          git commit -m "done"
          git push origin bukkit
