name: install bukkit
on: push
env:
  ver: 1.19.2
  ram: "6500M"
jobs:
  install-bukkit:
#    runs-on: ubuntu-latest
     runs-on: [ self-hosted ]
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4
      - name: install-bukkit
        run: |
          rm -rf work
          mkdir work 
          cd work
          git clone -b ${{ steps.branch-name.outputs.current_branch }} --single-branch https://${{ github.actor }}@github.com/${{ github.repository }}
          dir_name=$(basename ${{ github.repository }} /)
          cd $dir_name
          mkdir out
          mkdir out/bukkit
          cd out/bukkit
          git init
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          cd ..
          cd ..
          for file in bukkit; do
            cp -r $file out/bukkit/
          done
          cd out/bukkit
          cd bukkit
          wget -O purpur.jar https://api.purpurmc.org/v2/purpur/${{ env.ver }}/latest/download
          bash plugins.txt
          rm -r plugins.txt
          rm -r eula.txt
          touch eula.txt
          echo 'eula=true' >> eula.txt 
          rm -rf run.sh
          touch run.sh
          echo 'java -Xms${{ env.ram }} -Xmx${{ env.ram }} -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar purpur.jar nogui' >> run.sh
          chmod +x ./run.sh
          rm -rf plugins/stoponstart.jar 
          cd ..
          git checkout -b ${{ steps.branch-name.outputs.current_branch }}-bukkit
          git add .
          git commit -m "install done"
          git push origin ${{ steps.branch-name.outputs.current_branch }}-bukkit --force
