name: install bukkit
on: push
jobs:
  install-bukkit:
    runs-on: [ self-hosted, mc-home ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install docker
        run: sudo apt get install docker

      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "bukkit/*"
          target: "/home/mc/minecraft/test-bukkit"
